// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: createUser :one
insert into users (
  email
) values (
  $1
) returning id
`

func (q *Queries) createUser(ctx context.Context, email pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, email)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserPassword = `-- name: getUserPassword :one
select password from users
where username = $1
`

func (q *Queries) getUserPassword(ctx context.Context, username pgtype.Text) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getUserPassword, username)
	var password pgtype.Text
	err := row.Scan(&password)
	return password, err
}
