[vcs]
enabled = false
client_kind = "git"
use_ignore_file = false

[files]
ignore = []

[linter]
enabled = true

[linter.rules]
recommended = true

[linter.rules.safety]
banDropTable = "off"

[db]
host = "127.0.0.1"
port = 5432
username = "grant"
# password = "postgres"
database = "shrimp_server"
conn_timeout_secs = 10
